CI: Add Ruby summary job, for branch protection rules

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,3 +32,14 @@ jobs:
           bundler-cache: true
       - name: Sorbet
         run: bundle exec srb typecheck
+  # Ruby summary job, for branch protection rules
+  # Head ruby failures are ignored due to continue-on-error in the test job.
+  all-tests:
+    name: Ruby (non-head) tests passed
+    runs-on: ubuntu-latest
+    needs: [test]
+    if: always()
+    steps:
+      - name: Check test results
+        run: |
+          [[ "${{ needs.test.result }}" == "success" ]] || exit 1
